#:schema ./.aviutl2-cli/aviutl2.schema.json

[project]
id = "flowrebmitmk2-a11y.aviutl2-psdtoolkit2-ext"
name = "aviutl2-psdtoolkit2-ext"
version = "0.1.0"

[development]
aviutl2_version = "latest"

[artifacts.psdtoolkitext-lua]
destination = "Script/PSDToolKitExt.lua"
source = "data/Script/PSDToolKitExt.lua"

[artifacts.psdtoolkitext-obj2]
destination = "Script/@PSDToolKitExt.obj2"
source = "data/Script/@PSDToolKitExt.obj2"

[artifacts.psdtoolkitext-anm2]
destination = "Script/@PSDToolKitExt.anm2"
source = "data/Script/@PSDToolKitExt.anm2"

[release]
zip_name = "aviutl2-psdtoolkit2-ext-v{version}"
package_information = "{name} v{version} / PSDToolKitExt files for AviUtl2"
