--- PSDToolKit.lua v2.0.0alpha10 by oov
--- DO NOT EDIT - This file is automatically generated.
package.preload['PSDToolKit.Animations'] = function(...)
--- Animations module for PSDToolKit
local SubObjectStates = require("PSDToolKit.SubObjectStates")
local easing = require("PSDToolKit.easing")
local debug = require("PSDToolKit.debug")
local dbg = debug.dbg

local Animations = {}

local easing_by_index = {
	[0] = easing.linear, -- None (same as linear)
	[1] = easing.linear,
	[2] = easing.sineIn,
	[3] = easing.sineOut,
	[4] = easing.sineInOut,
	[5] = easing.quadIn,
	[6] = easing.quadOut,
	[7] = easing.quadInOut,
	[8] = easing.cubicIn,
	[9] = easing.cubicOut,
	[10] = easing.cubicInOut,
	[11] = easing.quartIn,
	[12] = easing.quartOut,
	[13] = easing.quartInOut,
	[14] = easing.quintIn,
	[15] = easing.quintOut,
	[16] = easing.quintInOut,
	[17] = easing.expoIn,
	[18] = easing.expoOut,
	[19] = easing.expoInOut,
	[20] = easing.backIn,
	[21] = easing.backOut,
	[22] = easing.backInOut,
	[23] = easing.elasticIn,
	[24] = easing.elasticOut,
	[25] = easing.elasticInOut,
	[26] = easing.bounceIn,
	[27] = easing.bounceOut,
	[28] = easing.bounceInOut,
}

--- Applies bounce animation.
-- @param opts table: Options (id, duration, interval, speed, size, vert, horz)
-- @param obj table: The AviUtl object
function Animations.bounce(opts, obj)
	if opts == nil then
		error("opts cannot be nil")
	end
	local id = opts.id
	if id == nil or id == "" then
		return
	end

	local subobj = SubObjectStates:get(id)
	if subobj == nil then
		return
	end

	local duration = opts.duration or 0.30
	local interval = opts.interval or 0.03
	local speed = opts.speed or 0.1
	local size = opts.size or 5
	local vert = opts.vert or 1
	local horz = opts.horz or 1

	local p = math.max(0, math.min(1, (duration - subobj.time + obj.index * interval) / duration))
	if p == 0 or p == 1 then
		return
	end

	local scale = math.sin(math.pi * (subobj.time - obj.index * interval) / speed)
	local z = obj.zoom
	obj.zoom = obj.zoom + scale * size * 0.01 * p

	if horz ~= 1 then
		local ofs = (obj.w * obj.zoom - obj.w * z) * 0.5
		obj.ox = obj.ox + (horz == 0 and ofs or -ofs)
	end
	if vert ~= 1 then
		local ofs = (obj.h * obj.zoom - obj.h * z) * 0.5
		obj.oy = obj.oy + (vert == 0 and ofs or -ofs)
	end
end

--- Applies enter/exit animation.
-- @param opts table: Options
--   id: Character ID
--   speed: Animation duration in seconds (default: 0.30)
--   interval: Delay between characters in seconds (default: 0.03)
--   alpha: Target alpha 0-100 (default: 100)
--   ein: Enter easing 0=None, 1=Linear, 2=SineIn, 3=SineOut, ... (default: 3)
--   eout: Exit easing 0=None, 1=Linear, 2=SineIn, 3=SineOut, ... (default: 2)
--   outside: Behavior when outside SubObject range 0=target, 1=normal (default: 0)
--   x, y, z: Position offset (default: 0)
--   sx, sy: Scale X/Y 0-100 (default: 100)
--   vert, horz: Scale anchor 0=top/left, 1=center, 2=bottom/right (default: 1)
--   rx, ry, rz: Rotation angles (default: 0)
-- @param obj table: The AviUtl object
function Animations.enter_exit(opts, obj)
	if opts == nil then
		error("opts cannot be nil")
	end
	local id = opts.id

	local subobj = nil
	if id ~= nil and id ~= "" then
		subobj = SubObjectStates:get(id)
	end

	local speed = opts.speed or 0.30
	local interval = opts.interval or 0.03
	local target_alpha = (opts.alpha or 100) / 100
	local ein = opts.ein or 3
	local eout = opts.eout or 2
	local outside = opts.outside or 0

	local x = opts.x or 0
	local y = opts.y or 0
	local z = opts.z or 0

	local sx = (opts.sx or 100) / 100
	local sy = (opts.sy or 100) / 100

	local vert = opts.vert or 1
	local horz = opts.horz or 1

	local rx = opts.rx or 0
	local ry = opts.ry or 0
	local rz = opts.rz or 0

	local ein_func = easing_by_index[ein] or easing.linear
	local eout_func = easing_by_index[eout] or easing.linear

	-- Calculate progress: p=1 normal, p=0 target
	local p
	if subobj == nil then
		p = outside ~= 0 and 0 or 1
	elseif speed > 0 then
		local exit_offset = (obj.num - obj.index - 1) * interval
		local sp = ein == 0 and 1 or 1 - math.max(0, math.min(1, (speed - subobj.time + obj.index * interval) / speed))
		local ep = eout == 0 and 1 or math.max(0, math.min(1, (subobj.totaltime - subobj.time - exit_offset) / speed))
		p = sp * ep
		dbg("enter_exit: sp=%f ep=%f p=%f speed=%f interval=%f", sp, ep, p, speed, interval)
		if p > 0 and p < 1 then
			if sp < 1 then
				p = ein_func(p)
			else
				p = eout_func(p)
			end
		end
	else
		p = 1
	end

	obj.alpha = math.max(0, math.min(1, obj.alpha * p + obj.alpha * target_alpha * (1 - p)))
	obj.ox = obj.ox + x * (1 - p)
	obj.oy = obj.oy + y * (1 - p)
	obj.oz = obj.oz + z * (1 - p)

	local old_sx, old_sy = obj.sx, obj.sy
	obj.sx = obj.sx * p + obj.sx * sx * (1 - p)
	obj.sy = obj.sy * p + obj.sy * sy * (1 - p)

	if horz ~= 1 then
		local ofs = obj.w * (old_sx - obj.sx) * 0.5
		obj.ox = obj.ox + (horz == 0 and -ofs or ofs)
	end
	if vert ~= 1 then
		local ofs = obj.h * (old_sy - obj.sy) * 0.5
		obj.oy = obj.oy + (vert == 0 and -ofs or ofs)
	end

	local old_rx = obj.rx
	obj.rx = obj.rx * p + rx * (1 - p)
	local old_ry = obj.ry
	obj.ry = obj.ry * p + ry * (1 - p)
	local old_rz = obj.rz
	obj.rz = obj.rz * p + rz * (1 - p)

	-- X-axis rotation pivot adjustment (affects oy/oz based on vert)
	if vert ~= 1 and obj.rx ~= old_rx then
		local pivot_y = vert == 0 and obj.h * old_sy * 0.5 or -obj.h * old_sy * 0.5
		local rad = math.rad(obj.rx - old_rx)
		local cos_r, sin_r = math.cos(rad), math.sin(rad)
		local rotated_y = pivot_y * cos_r
		local rotated_z = pivot_y * sin_r
		obj.oy = obj.oy + (rotated_y - pivot_y)
		obj.oz = obj.oz + rotated_z
	end

	-- Y-axis rotation pivot adjustment (affects ox/oz based on horz)
	if horz ~= 1 and obj.ry ~= old_ry then
		local pivot_x = horz == 0 and obj.w * old_sx * 0.5 or -obj.w * old_sx * 0.5
		local rad = math.rad(obj.ry - old_ry)
		local cos_r, sin_r = math.cos(rad), math.sin(rad)
		local rotated_x = pivot_x * cos_r
		local rotated_z = -pivot_x * sin_r
		obj.ox = obj.ox + (rotated_x - pivot_x)
		obj.oz = obj.oz + rotated_z
	end

	-- Z-axis rotation pivot adjustment (affects ox/oy based on horz/vert)
	if (horz ~= 1 or vert ~= 1) and obj.rz ~= old_rz then
		local pivot_x = horz == 0 and obj.w * old_sx * 0.5 or (horz == 2 and -obj.w * old_sx * 0.5 or 0)
		local pivot_y = vert == 0 and obj.h * old_sy * 0.5 or (vert == 2 and -obj.h * old_sy * 0.5 or 0)
		local rad = math.rad(obj.rz - old_rz)
		local cos_r, sin_r = math.cos(rad), math.sin(rad)
		local rotated_x = pivot_x * cos_r - pivot_y * sin_r
		local rotated_y = pivot_x * sin_r + pivot_y * cos_r
		obj.ox = obj.ox + (rotated_x - pivot_x)
		obj.oy = obj.oy + (rotated_y - pivot_y)
	end
end

return Animations

end

package.preload['PSDToolKit.Blinker'] = function(...)
--- Blinker (eye blink animator) for PSDToolKit v2.0.0alpha10 by oov
local Blinker = {}
Blinker.__index = Blinker

-- Display name keys for pattern parameters
-- Order: closed -> almost_closed -> half -> almost_open -> open
-- This order matches the animation logic where patterns[1] is closed (default)
-- and patterns[n] is open
local pattern_keys = {
	"閉じ~ptkl",
	"ほぼ閉じ~ptkl",
	"半開き~ptkl",
	"ほぼ開き~ptkl",
	"開き~ptkl",
}

--- Validate that at least 2 patterns are present.
-- @param patterns table: Patterns array
-- @return boolean: true if valid
local function validate(patterns)
	if #patterns < 2 then
		error("Blinker requires at least 2 patterns (closed and open)")
	end
	return true
end

--- Create a new Blinker object from legacy parameters.
-- This function is called from converted anm scripts.
-- @param patterns table: Array of layer state strings (2-5 elements, closed to open)
-- @param interval number: Animation interval in seconds (default: 4)
-- @param speed number: Animation speed in frames (default: 1)
-- @param offset number: Animation offset (default: 0)
-- @return Blinker object
function Blinker.new_legacy(patterns, interval, speed, offset)
	local opts = {
		["閉じ~ptkl"] = patterns[1],
		["開き~ptkl"] = patterns[#patterns],
		["間隔(秒)"] = tostring(interval or 4),
		["速さ"] = tostring(speed or 1),
		["オフセット"] = tostring(offset or 0),
	}
	if #patterns >= 3 then
		opts["ほぼ閉じ~ptkl"] = patterns[2]
	end
	if #patterns >= 4 then
		opts["半開き~ptkl"] = patterns[3]
	end
	if #patterns >= 5 then
		opts["ほぼ開き~ptkl"] = patterns[4]
	end
	return Blinker.new(opts)
end

--- Create a new Blinker object.
-- @param opts table: Options table with display name keys
--   Pattern keys (values are layer paths):
--     "閉じ~ptkl": Closed state
--     "ほぼ閉じ~ptkl": Almost closed state (optional)
--     "半開き~ptkl": Half open state (optional)
--     "ほぼ開き~ptkl": Almost open state (optional)
--     "開き~ptkl": Open state
--   Numeric parameters (stored as strings):
--     "間隔(秒)": Animation interval in seconds (default: 4)
--     "速さ": Animation speed (frames per pattern) (default: 1)
--     "オフセット": Animation start offset (default: 0)
-- @return Blinker object
function Blinker.new(opts)
	if not opts then
		error("opts cannot be nil")
	end

	-- Build patterns array from display name keys
	-- Collect non-empty patterns in order
	local patterns = {}
	for _, key in ipairs(pattern_keys) do
		local value = opts[key]
		if value and value ~= "" then
			table.insert(patterns, value)
		end
	end

	if #patterns > 3 then
		-- Insert "almost open" at the beginning for asymmetric animation:
		-- Original patterns: closed, almost_closed, half, almost_open, open
		-- After insert: almost_open, closed, almost_closed, half, almost_open, open
		-- This creates: open -> almost_open -> closed -> almost_closed -> half -> almost_open -> open
		-- The quick transition from almost_open to closed makes the blink look natural
		table.insert(patterns, 1, patterns[#patterns - 1])
	end

	-- Parse numeric parameters (stored as strings)
	local interval = tonumber(opts["間隔(秒)"]) or 4
	local speed = tonumber(opts["速さ"]) or 1
	local offset = tonumber(opts["オフセット"]) or 0

	return setmetatable({
		patterns = patterns,
		interval = interval,
		speed = speed,
		offset = offset,
	}, Blinker)
end

--- Get current layer state for animation.
-- @param ctx table: Context object with obj and psd properties
-- @return string: The current pattern string
function Blinker:getstate(ctx)
	validate(self.patterns)
	local obj = ctx.obj
	local interval = self.interval * obj.framerate + self.speed * #self.patterns * 2
	local basetime = obj.frame + interval + self.offset
	local blink = basetime % interval
	local blink2 = (basetime + self.speed * #self.patterns) % (interval * 5)
	for i, v in ipairs(self.patterns) do
		local l = self.speed * i
		local r = l + self.speed
		if (l <= blink and blink < r) or (l <= blink2 and blink2 < r) then
			return v
		end
	end
	return self.patterns[#self.patterns]
end

return Blinker

end

package.preload['PSDToolKit.CharacterID'] = function(...)
--- CharacterID utilities for PSDToolKit
-- Provides common functions for converting character IDs and layer numbers to storage keys.
-- Character ID can be:
--   - A named ID like "foo" (stored as "_foo")
--   - A layer number like "L3" (stored as "L3")
--   - Multiple IDs separated by commas like "foo,bar"
local M = {}

--- Converts a single character ID to a storage key for retrieval.
-- @param id string: The character ID (e.g., "foo", "L3"). Must not be nil or empty.
-- @return string: The storage key
local function to_key(id)
	-- Check if id matches "L[0-9]+" pattern (layer number)
	if id:match("^L%d+$") then
		return id
	end
	-- Otherwise, it's a named character ID
	return "_" .. id
end

--- Converts a layer number to a storage key.
-- @param layer number: The layer number
-- @return string: The storage key (e.g., "L3")
local function layer_to_key(layer)
	return "L" .. tostring(layer)
end

--- Iterates over each ID in a comma-separated string and calls the callback with the storage key.
-- @param id string|nil: The character identifier(s), comma-separated
-- @param callback function: Called with each storage key (e.g., "_foo", "_bar")
local function each_id_key(id, callback)
	if id == nil or id == "" then
		return
	end
	for single_id in string.gmatch(id, "([^,]+)") do
		-- Trim whitespace from each id
		single_id = single_id:match("^%s*(.-)%s*$")
		if single_id ~= "" then
			callback(to_key(single_id))
		end
	end
end

--- Gets a value from states by character ID (supports comma-separated fallback search).
-- @param states table: The states table to search
-- @param id string: The character ID(s), comma-separated for fallback search
-- @return any: The first found value, or nil if not found
function M.get(states, id)
	if id == nil or id == "" then
		return nil
	end
	local result = nil
	each_id_key(id, function(key)
		if result == nil then
			result = states[key]
		end
	end)
	return result
end

--- Sets a value in states for both layer key and character ID keys.
-- @param states table: The states table to store into
-- @param id string|nil: The character identifier(s), comma-separated
-- @param layer number: The layer number
-- @param value any: The value to set
function M.set(states, id, layer, value)
	states[layer_to_key(layer)] = value
	each_id_key(id, function(key)
		states[key] = value
	end)
end

--- Calls a callback for each key (layer key and character ID keys).
-- @param id string|nil: The character identifier(s), comma-separated
-- @param layer number: The layer number
-- @param fn function: Called with each storage key
function M.set_callback(id, layer, fn)
	fn(layer_to_key(layer))
	each_id_key(id, fn)
end

return M

end

package.preload['PSDToolKit.Context'] = function(...)
--- Context module for PSDToolKit
-- Provides context object for state evaluation (LipSync, Blinker, etc.)
local Context = {}

local LabFile = require("PSDToolKit.LabFile")
local voice_states = require("PSDToolKit.VoiceStates")
local overwriter_states = require("PSDToolKit.OverwriterStates")

-- Audio level cache (cleared each frame when context is created)
local audio_cache = {}

--- Calculate audio level from pre-captured fourier data in Voice object.
-- @param voice table: Voice object with fourier_data, fourier_sample_rate, fourier_n
-- @param locut number: Low frequency cutoff (Hz)
-- @param hicut number: High frequency cutoff (Hz)
-- @return number: Audio level
local function calculate_audio_level_from_voice(voice, locut, hicut)
	if not voice then
		return 0
	end

	local buf = voice.fourier_data
	local sample_rate = voice.fourier_sample_rate
	local n = voice.fourier_n

	if not buf or not sample_rate or not n or n == 0 then
		return 0
	end

	-- Calculate frequency per bin
	local freq_per_bin = sample_rate / 2048

	-- Calculate bin range for locut/hicut
	local lo_bin = math.floor(locut / freq_per_bin)
	local hi_bin = math.ceil(hicut / freq_per_bin)

	-- Clamp to valid range (1 to n)
	if lo_bin < 1 then
		lo_bin = 1
	end
	if hi_bin > n then
		hi_bin = n
	end

	-- Sum amplitude in the frequency range
	local sum = 0
	local count = 0
	for i = lo_bin, hi_bin do
		sum = sum + math.abs(buf[i] or 0)
		count = count + 1
	end

	if count == 0 then
		return 0
	end

	return sum / count
end

--- Create a context object for state evaluation.
-- @param psd table: The PSD object
-- @param obj table: The AviUtl object
-- @return table: Context object with get_voice and get_audio_level methods
function Context.new(psd, obj)
	-- Clear audio cache for new frame
	audio_cache = {}

	local ctx = {
		obj = obj,
		psd = psd,
	}

	--- Get voice by ID.
	-- @param id string|number: Character ID or layer number (required)
	-- @return table|nil: Voice object or nil
	function ctx:get_voice(id)
		if id == nil then
			error("id is required")
		end
		return voice_states:get(id)
	end

	--- Get audio level from Voice object's pre-captured fourier data.
	-- The fourier data is captured in set_voice() at the correct audio timing.
	-- @param voice_id string|number: Voice ID to look up
	-- @param locut number: Low frequency cutoff (Hz)
	-- @param hicut number: High frequency cutoff (Hz)
	-- @return number: Audio level
	function ctx:get_audio_level(voice_id, locut, hicut)
		if voice_id == nil then
			error("voice_id is required")
		end
		if locut == nil then
			error("locut is required")
		end
		if hicut == nil then
			error("hicut is required")
		end

		-- Create cache key using voice_id
		local key = tostring(voice_id) .. ":" .. tostring(locut) .. ":" .. tostring(hicut)
		if audio_cache[key] then
			return audio_cache[key]
		end

		-- Get voice and calculate level from pre-captured fourier data
		local voice = voice_states:get(voice_id)
		local level = calculate_audio_level_from_voice(voice, locut, hicut)
		audio_cache[key] = level
		return level
	end

	--- Get overwriter values by character ID.
	-- @param id string: Character ID (can be nil or empty for default)
	-- @return table|nil: Overwriter values table {p1=number, ...}, or nil if not found
	function ctx:get_overwriter(id)
		return overwriter_states:get(id)
	end

	--- Get phoneme info from lab file at current voice time.
	-- The lab file path is derived from the voice's audio path by replacing
	-- the extension with .lab.
	-- @param voice_id string|number: Voice ID to look up
	-- @return table|nil: Phoneme info from LabFile.get_phoneme_at(), or nil if
	--   voice not found, no audio path, or lab file not found/parseable.
	--   See LabFile.get_phoneme_at() for return value structure.
	function ctx:get_phoneme(voice_id)
		local debug = require("PSDToolKit.debug")
		local dbg = debug.dbg

		if voice_id == nil then
			error("voice_id is required")
		end

		local voice = voice_states:get(voice_id)
		if not voice then
			dbg("get_phoneme: voice not found for id=%s", tostring(voice_id))
			return nil
		end
		if not voice.audio or voice.audio == "" then
			dbg("get_phoneme: voice.audio is empty for id=%s", tostring(voice_id))
			return nil
		end

		-- Convert audio path to lab path (replace extension with .lab)
		local lab_path = voice.audio:gsub("%.[^.]+$", ".lab")
		dbg("get_phoneme: lab_path=%s time=%.4f", lab_path, voice.time or -1)

		-- Get phoneme at voice's current time
		local result = LabFile.get_phoneme_at(lab_path, voice.time)
		if not result then
			dbg("get_phoneme: LabFile.get_phoneme_at returned nil")
		end
		return result
	end

	return ctx
end

return Context

end

package.preload['PSDToolKit.CurrentPSD'] = function(...)
--- CurrentPSD - Current PSD instance management (singleton)
-- Manages the current PSD object being processed in the current frame.
-- States are organized by frame number to support multi-frame state management.
-- Provides functions to initialize, draw, and add states to the current PSD.
local CurrentPSD = {}

local debug = require("PSDToolKit.debug")
local dbg = debug.dbg
local i18n = require("PSDToolKit.i18n").i18n
local FrameState = require("PSDToolKit.FrameState")
local PSD = require("PSDToolKit.PSD")
local LayerSelector = require("PSDToolKit.LayerSelector")
local ValueCache = require("PSDToolKit.ValueCache")

local currents = {} -- frame_number -> psd

--- Clear the PSD reference for a specific frame.
-- @param frame_number number: The frame number to clean up
function CurrentPSD.cleanup_frame(frame_number)
	currents[frame_number] = nil
end

--- Clear all PSD references (for cache invalidation).
function CurrentPSD.clear_all()
	currents = {}
end

--- Get the current PSD object.
-- @return PSD|nil: The current PSD object, or nil if not initialized
function CurrentPSD.get()
	local frame = FrameState.get_current_frame()
	return currents[frame]
end

--- Get the current PSD object, or error if not initialized.
-- @return PSD: The current PSD object
function CurrentPSD.require()
	local frame = FrameState.get_current_frame()
	local current = currents[frame]
	if not current then
		error(i18n({
			ja_JP = "PSDが初期化されていません。init_psdを先に呼び出してください。",
			en_US = "No PSD initialized. Call init_psd first.",
			zh_CN = "PSD未初始化。请先调用init_psd。",
		}))
	end
	return current
end

--- Initialize a PSD object for the current layer.
-- @param opts table: Options {file=string, scene=number, tag=number, layer=string, scale=number, offsetx=number, offsety=number, character_id=string}
-- @param obj table: The AviUtl object
-- @return PSD: The initialized PSD object
function CurrentPSD.init(opts, obj)
	if not opts then
		error("opts cannot be nil")
	end
	if not opts.file or opts.file == "" then
		error("opts.file is required")
	end

	local ptk = obj.module("PSDToolKit")
	if not ptk then
		error("PSDToolKit script module is not available")
	end

	-- Generate unique ID using PSD.make_id (includes validation)
	local scene = opts.scene or 0
	local id = PSD.make_id(scene, obj.layer)

	-- Generate tag if not provided
	local tag = opts.tag
	if not tag or tag == 0 then
		tag = ptk.generate_tag()
	end

	-- Add PSD file to Go process
	local ok = ptk.add_psd_file(opts.file, tag)
	if not ok then
		error("failed to add PSD file")
	end

	-- Create PSD object
	local psd = PSD.new(id, opts.file, tag, {
		layer = opts.layer,
		scale = opts.scale,
		offsetx = opts.offsetx,
		offsety = opts.offsety,
		character_id = opts.character_id,
	})

	dbg(
		"CurrentPSD.init: id=%s file=%s tag=%s character_id=%s",
		tostring(id),
		tostring(opts.file),
		tostring(tag),
		tostring(opts.character_id)
	)

	-- Store reference for current frame
	local frame = FrameState.get_current_frame()
	FrameState.track_frame_access(frame)
	currents[frame] = psd

	return psd
end

--- Draw the current PSD object.
-- @param obj table: The AviUtl object
function CurrentPSD.draw(obj)
	if FrameState.has_error() then
		return
	end
	-- Skip expensive PSD rendering when fully transparent (e.g. enter_exit with extreme threshold)
	if obj.alpha <= 0 then
		return
	end
	local frame = FrameState.get_current_frame()
	local current = currents[frame]
	if not current then
		error(i18n({
			ja_JP = "「PSDファイル@PSDToolKit」が配置されていません。",
			en_US = "'PSDファイル@PSDToolKit' is not placed.",
			zh_CN = "未放置「PSDファイル@PSDToolKit」。",
		}))
	end
	current:draw(obj)
end

--- Add a lip sync state to the current PSD.
-- @param opts table: Options with display name keys (passed directly to LipSync.new)
-- @param obj table: The AviUtl object
function CurrentPSD.add_lipsync(opts, obj)
	if FrameState.has_error() then
		return
	end
	local psd = CurrentPSD.require()
	if not opts then
		error("opts cannot be nil")
	end

	local LipSync = require("PSDToolKit.LipSync")
	local lipsync = LipSync.new(opts)

	psd:add_state(lipsync)
	dbg("CurrentPSD.add_lipsync")
end

--- Add a vowel-based lip sync (aiueo) state to the current PSD.
-- @param opts table: Options with display name keys (passed directly to LipSyncLab.new)
-- @param obj table: The AviUtl object
function CurrentPSD.add_lipsync_lab(opts, obj)
	if FrameState.has_error() then
		return
	end
	local psd = CurrentPSD.require()
	if not opts then
		error("opts cannot be nil")
	end

	local LipSyncLab = require("PSDToolKit.LipSyncLab")
	local lipsync = LipSyncLab.new(opts)

	psd:add_state(lipsync)
	dbg("CurrentPSD.add_lipsync_lab")
end

--- Add a blinker (eye blink) state to the current PSD.
-- @param opts table: Options with display name keys (passed directly to Blinker.new)
-- @param obj table: The AviUtl object
function CurrentPSD.add_blinker(opts, obj)
	if FrameState.has_error() then
		return
	end
	local psd = CurrentPSD.require()
	if not opts then
		error("opts cannot be nil")
	end

	local Blinker = require("PSDToolKit.Blinker")
	local blinker = Blinker.new(opts)

	psd:add_state(blinker)
	dbg("CurrentPSD.add_blinker")
end

--- Add a layer selector state to the current PSD.
-- Uses ValueCache internally to cache factory results.
-- @param part_index number: Explicit part index for this selector (1, 2, 3, ...)
-- @param factory function: Factory function that returns array of layer state strings
-- @param selected number: Index of the selected layer (1-based)
-- @param opts table|nil: Optional parameters {exclusive=boolean}
function CurrentPSD.add_layer_selector(part_index, factory, selected, opts)
	if FrameState.has_error() then
		return
	end
	local psd = CurrentPSD.require()
	if type(part_index) ~= "number" then
		error("part_index must be a number")
	end
	if type(factory) ~= "function" then
		error("factory must be a function")
	end

	opts = opts or {}
	local exclusive = opts.exclusive or false

	-- Cache key includes exclusive flag to separate cached values
	local effect_key = obj.effect_id .. (exclusive and "_1" or "_0")

	-- Wrap factory to build exclusive values if needed
	local wrapped_factory
	if exclusive then
		wrapped_factory = function()
			return LayerSelector.build_exclusive_values(factory())
		end
	else
		wrapped_factory = factory
	end

	-- Get cached values
	local values = ValueCache.get(effect_key, part_index, wrapped_factory)

	if not values or #values < 1 then
		error("factory must return at least 1 value")
	end

	local selector = LayerSelector.new(values, selected, {
		character_id = psd.character_id,
		part_index = part_index,
	})

	psd:add_state(selector)
	dbg(
		"CurrentPSD.add_layer_selector part_index=%d values=%d selected=%s character_id=%s exclusive=%s",
		part_index,
		#values,
		tostring(selected),
		tostring(psd.character_id),
		tostring(exclusive)
	)
end

--- Add layer state to the current PSD.
-- @param layer string|table: Layer state string or table with getstate method, or a list of layer states
-- @param index number|nil: If provided with a list, select layer[index]
function CurrentPSD.add_state(layer, index)
	if FrameState.has_error() then
		return
	end
	local psd = CurrentPSD.require()
	psd:add_state(layer, index)
end

--- Add layer state to the current PSD (legacy API).
-- This function is called from converted AviUtl1 *.anm scripts via PSD:addstate().
-- Supports two calling conventions:
--   add_state_legacy(values, selected_index) - table with index
--   add_state_legacy("layer/path") - single string
-- @param values table|string: Array of layer state strings, or a single layer state string
-- @param selected number|nil: Index of the selected layer (1-based), only used when values is a table
function CurrentPSD.add_state_legacy(values, selected)
	CurrentPSD.add_state(values, selected)
end

return CurrentPSD

end

package.preload['PSDToolKit.FrameState'] = function(...)
--- FrameState - Per-frame state management (singleton)
-- Manages frame-level state such as initialization status and error state.
-- Also tracks recently accessed frames for multi-frame state management.
-- This module is used by init.lua and other modules that need to check
-- whether the current frame has been properly initialized.
local FrameState = {}

local initialized = false
local has_error = false

-- Frame tracking for multi-frame state management
local MAX_RECENT_FRAMES = 4
local recent_frames = {} -- Array of {frame=number, access_order=number}
local access_counter = 0 -- Monotonically increasing counter for LRU-like ordering

--- Clear frame state for a new frame.
-- Called at the beginning of each frame processing.
function FrameState.clear()
	initialized = true
	has_error = false
end

--- Check if the frame has been initialized.
-- @return boolean: true if new_frame() has been called for this frame
function FrameState.is_initialized()
	return initialized
end

--- Check if an error has occurred during frame processing.
-- @return boolean: true if an error has been set
function FrameState.has_error()
	return has_error
end

--- Set the error state.
-- Once set, has_error() will return true until the next clear().
function FrameState.set_error()
	has_error = true
end

--- Get the current project frame number.
-- This returns the absolute frame number in the project (not object-relative).
-- @return number: The current frame number
function FrameState.get_current_frame()
	return obj.getvalue("frame_s") + obj.frame
end

--- Track that a frame was accessed (for data registration).
-- This is called when data is registered for a specific frame.
-- @param frame_number number: The frame number that was accessed
function FrameState.track_frame_access(frame_number)
	access_counter = access_counter + 1

	-- Check if frame already tracked, update access order
	for _, entry in ipairs(recent_frames) do
		if entry.frame == frame_number then
			entry.access_order = access_counter
			return
		end
	end

	-- Add new frame
	table.insert(recent_frames, {
		frame = frame_number,
		access_order = access_counter,
	})
end

--- Get frames to cleanup (frames not in the most recent MAX_RECENT_FRAMES).
-- Returns and removes stale frame entries from tracking.
-- @return table: Array of frame numbers to clean up
function FrameState.get_frames_to_cleanup()
	if #recent_frames <= MAX_RECENT_FRAMES then
		return {}
	end

	-- Sort by access_order (oldest first)
	table.sort(recent_frames, function(a, b)
		return a.access_order < b.access_order
	end)

	-- Collect frames to remove (all but the last MAX_RECENT_FRAMES)
	local to_cleanup = {}
	local remove_count = #recent_frames - MAX_RECENT_FRAMES
	for i = 1, remove_count do
		table.insert(to_cleanup, recent_frames[i].frame)
	end

	-- Remove from tracking
	for _ = 1, remove_count do
		table.remove(recent_frames, 1)
	end

	return to_cleanup
end

--- Clear all frame tracking data.
-- Called when cache is invalidated (project load or cache clear).
function FrameState.clear_all_frames()
	recent_frames = {}
	access_counter = 0
end

return FrameState

end

package.preload['PSDToolKit.LabFile'] = function(...)
--- LabFile - LAB file parser with LRU cache
-- Parses .lab files (phoneme timing data) and caches results.
-- LAB file format: each line contains "start_time end_time phoneme"
-- where times are in 100-nanosecond units (1e7 per second).
local LabFile = {}

-- Time unit: 100 nanoseconds (1e7 per second)
-- Change this value if lab file uses different unit
local TIME_UNIT = 10000000

-- LRU cache
local cache = {} -- {[labpath] = entries}
local cache_order = {} -- oldest first (for LRU eviction)
local MAX_CACHE_SIZE = 4

--- Update LRU order (move to end = most recently used)
-- @param labpath string: Path to lab file
local function touch_cache(labpath)
	-- Remove existing entry from order
	for i = #cache_order, 1, -1 do
		if cache_order[i] == labpath then
			table.remove(cache_order, i)
			break
		end
	end
	-- Add to end (most recently used)
	table.insert(cache_order, labpath)
end

--- Evict oldest cache entry if over limit
local function evict_if_needed()
	while #cache_order > MAX_CACHE_SIZE do
		local oldest = table.remove(cache_order, 1)
		cache[oldest] = nil
	end
end

--- Parse a lab file
-- @param labpath string: Path to .lab file
-- @return table|nil: Array of {start=number, end_=number, phoneme=string}
--   Times are converted to seconds. Returns nil if file cannot be opened.
local function parse_lab_file(labpath)
	local debug = require("PSDToolKit.debug")
	local dbg = debug.dbg

	-- Use script module's read_text_file for proper UTF-8 path handling on Windows
	local ptk = obj.module("PSDToolKit")
	if not ptk then
		dbg("parse_lab_file: PSDToolKit script module not available")
		return nil
	end

	local content = ptk.read_text_file(labpath)
	if content == nil then
		dbg("parse_lab_file: failed to open file: %s", labpath)
		return nil
	end

	local entries = {}
	local line_count = 0
	for line in content:gmatch("[^\r\n]+") do
		line_count = line_count + 1
		local st, ed, p = string.match(line, "([0-9.]+)%s+([0-9.]+)%s+(.+)")
		if st and ed and p then
			-- Trim whitespace from phoneme
			p = p:match("^%s*(.-)%s*$")
			local start_sec = tonumber(st) / TIME_UNIT
			local end_sec = tonumber(ed) / TIME_UNIT
			table.insert(entries, {
				start = start_sec,
				end_ = end_sec,
				phoneme = p,
			})
			if #entries <= 3 then
				dbg(
					"parse_lab_file: entry[%d] raw=%s,%s,%s -> start=%.4f end=%.4f phoneme=%s",
					#entries,
					st,
					ed,
					p,
					start_sec,
					end_sec,
					p
				)
			end
		else
			if line_count <= 3 then
				dbg("parse_lab_file: line %d did not match pattern: [%s]", line_count, line)
			end
		end
	end

	dbg("parse_lab_file: parsed %d entries from %s", #entries, labpath)
	return entries
end

--- Get or parse lab file with caching
-- @param labpath string: Path to .lab file
-- @return table|nil: Cached entries array, or nil if file not found
function LabFile.get_entries(labpath)
	-- Check cache first
	local entries = cache[labpath]
	if entries then
		touch_cache(labpath)
		return entries
	end

	-- Parse file
	entries = parse_lab_file(labpath)
	if entries == nil then
		return nil
	end

	-- Store in cache
	cache[labpath] = entries
	touch_cache(labpath)
	evict_if_needed()

	return entries
end

--- Binary search for phoneme at given time
-- @param entries table: Parsed entries array (sorted by start time)
-- @param time number: Time in seconds
-- @return number|nil: Index of entry containing time (1-based), or nil if not found
local function binary_search(entries, time)
	local lo, hi = 1, #entries
	while lo <= hi do
		local mid = math.floor((lo + hi) / 2)
		local entry = entries[mid]
		if time < entry.start then
			hi = mid - 1
		elseif time >= entry.end_ then
			lo = mid + 1
		else
			-- entry.start <= time < entry.end_
			return mid
		end
	end
	return nil -- Not found (time outside all entries)
end

--- Clear the LRU cache.
function LabFile.clear()
	cache = {}
	cache_order = {}
end

--- Get phoneme info at specified time
-- @param labpath string: Path to .lab file
-- @param time number: Current time in seconds
-- @return table|nil: {
--   index = number,      -- 1-based index in entries
--   phoneme = string,    -- Current phoneme name
--   start = number,      -- Start time (seconds)
--   end_ = number,       -- End time (seconds)
--   duration = number,   -- Duration (seconds)
--   progress = number,   -- Progress within phoneme (0.0-1.0)
--   entries = table,     -- Reference to cached entries array
-- }
-- Returns nil if file not found or time is outside all entries.
function LabFile.get_phoneme_at(labpath, time)
	local debug = require("PSDToolKit.debug")
	local dbg = debug.dbg

	local entries = LabFile.get_entries(labpath)
	if entries == nil then
		dbg("get_phoneme_at: entries is nil for %s", labpath)
		return nil
	end
	if #entries == 0 then
		dbg("get_phoneme_at: entries is empty for %s", labpath)
		return nil
	end

	dbg(
		"get_phoneme_at: searching time=%.4f in %d entries (range %.4f - %.4f)",
		time,
		#entries,
		entries[1].start,
		entries[#entries].end_
	)

	local index = binary_search(entries, time)
	if index == nil then
		dbg("get_phoneme_at: binary_search returned nil (time outside range)")
		return nil
	end

	local entry = entries[index]
	local duration = entry.end_ - entry.start
	local progress = 0
	if duration > 0 then
		progress = (time - entry.start) / duration
	end

	dbg("get_phoneme_at: found index=%d phoneme=%s", index, entry.phoneme)

	return {
		index = index,
		phoneme = entry.phoneme,
		start = entry.start,
		end_ = entry.end_,
		duration = duration,
		progress = progress,
		entries = entries,
	}
end

return LabFile

end

package.preload['PSDToolKit.LayerSelector'] = function(...)
--- LayerSelector - Simple layer state selector for PSDToolKit v2.0.0alpha10 by oov
-- This module selects a layer state from a predefined list based on an index.
-- It is designed to work with layer selector scripts exported from the GUI.
local LayerSelector = {}
LayerSelector.__index = LayerSelector

local debug = require("PSDToolKit.debug")
local dbg = debug.dbg

-- Wrapper for objects with getstate method in exclusive mode.
-- Prepends hide prefix to the result of inner:getstate().
local ExclusiveWrapper = {}
ExclusiveWrapper.__index = ExclusiveWrapper

function ExclusiveWrapper.new(hide_prefix, inner)
	return setmetatable({
		hide_prefix = hide_prefix,
		inner = inner,
	}, ExclusiveWrapper)
end

function ExclusiveWrapper:getstate(ctx)
	local state = self.inner:getstate(ctx)
	if type(state) == "string" and state ~= "" then
		return self.hide_prefix .. " " .. state
	elseif type(state) == "table" then
		-- Array of strings - prepend to each string
		local result = {}
		for i, s in ipairs(state) do
			if type(s) == "string" and s ~= "" then
				result[i] = self.hide_prefix .. " " .. s
			else
				result[i] = s
			end
		end
		return result
	end
	return state
end

--- Check if a layer path has an exclusive marker (*) in the final component.
-- The marker must be at the start of the final path component after the last '/'.
-- Examples:
--   "v1.eye/*01" -> true (marker on final component)
--   "v1.*eye/01" -> false (marker on non-final component)
--   "v1.eye/01" -> false (no marker)
-- @param path string: A single layer path (e.g., "v1.eye/01")
-- @return boolean: true if the final component has the exclusive marker
function LayerSelector.has_exclusive_marker(path)
	-- Find the last '/' to get the final component
	local last_slash = path:match(".*()/")
	local final_component
	if last_slash then
		final_component = path:sub(last_slash + 1)
	else
		-- No slash, check after the visibility prefix (v0. or v1.)
		final_component = path:match("^v[01]%.(.*)$") or path
	end
	-- Check if final component starts with '*'
	return final_component:sub(1, 1) == "*"
end

--- Build exclusive values array from raw values.
-- For each value, prepend hide commands for ALL string values.
-- If any string value has exclusive marker (*), returns raw_values unchanged.
-- Non-string values (objects like Blinker, LipSync) are passed through unchanged.
-- @param raw_values table: Array of layer state strings or objects
-- @return table: Array of transformed layer state strings with exclusive prefix
function LayerSelector.build_exclusive_values(raw_values)
	-- First pass: collect hide strings (v0 converted) and check for markers
	local hide_parts = {}
	for _, value in ipairs(raw_values) do
		if type(value) == "string" then
			-- If any string has exclusive marker, return raw_values unchanged
			if LayerSelector.has_exclusive_marker(value) then
				return raw_values
			end
			local hidden = value:gsub("^v1%.", "v0.")
			table.insert(hide_parts, hidden)
		end
	end

	-- No string values means nothing to do
	if #hide_parts == 0 then
		return raw_values
	end

	local hide_prefix = table.concat(hide_parts, " ")

	-- Build result: for each value, prepend hide prefix if it's a string,
	-- or wrap with ExclusiveWrapper if it's an object with getstate method
	local result = {}
	for i, value in ipairs(raw_values) do
		if type(value) == "string" then
			result[i] = hide_prefix .. " " .. value
		elseif type(value) == "table" and type(value.getstate) == "function" then
			-- Wrap object to prepend hide_prefix to its getstate result
			result[i] = ExclusiveWrapper.new(hide_prefix, value)
		else
			-- Other non-string values pass through unchanged
			result[i] = value
		end
	end
	return result
end

--- Creates a new LayerSelector object.
-- @param values table: Array of layer state strings (already processed with exclusive prefix if needed)
-- @param selected number: Index of the selected layer (1-based, Lua convention)
-- @param opts table|nil: Optional parameters {character_id=string, part_index=number}
-- @return LayerSelector: New LayerSelector object
function LayerSelector.new(values, selected, opts)
	if not values then
		error("values cannot be nil")
	end
	if #values < 1 then
		error("LayerSelector requires at least 1 value")
	end

	opts = opts or {}

	-- Validate and clamp selected index
	local sel = selected or 0
	if sel < 0 then
		sel = 0
	elseif sel > #values then
		sel = #values
	end

	dbg(
		"LayerSelector.new: values=%d selected=%d part_index=%s character_id=%s",
		#values,
		sel,
		tostring(opts.part_index),
		tostring(opts.character_id)
	)

	return setmetatable({
		values = values,
		selected = sel,
		character_id = opts.character_id or "",
		part_index = opts.part_index or 0,
	}, LayerSelector)
end

--- Gets the current layer state.
-- This method is called from PSD:buildlayer() during animation rendering.
-- Checks for overwriter values and applies them if available.
-- @param ctx table: Context object with get_overwriter method
-- @return string: The selected layer state string
function LayerSelector:getstate(ctx)
	local sel = self.selected

	-- Check for overwriter values
	if self.part_index > 0 then
		local overwriter = ctx:get_overwriter(self.character_id)
		if overwriter then
			local key = "p" .. tostring(self.part_index)
			local override_value = overwriter[key]
			if override_value and override_value >= 1 and override_value <= #self.values then
				dbg("LayerSelector:getstate: overwrite %s from %d to %d", key, sel, override_value)
				sel = override_value
			end
		end
	end

	local state = self.values[sel]

	-- If state is an object with getstate method (e.g., Blinker, LipSync),
	-- call its getstate to get the actual layer string
	if type(state) == "table" and type(state.getstate) == "function" then
		state = state:getstate(ctx)
	end

	dbg("LayerSelector:getstate: selected=%d state=%s", sel, tostring(state))
	return state
end

return LayerSelector

end

package.preload['PSDToolKit.LipSync'] = function(...)
--- LipSync - Simple open/close lip sync
-- This module provides lip sync animation based on audio volume levels.
-- It uses a pattern system with 2-5 states (closed to fully open).
local LipSync = {}
LipSync.__index = LipSync

local debug = require("PSDToolKit.debug")
local dbg = debug.dbg

-- Per-layer state cache for smooth animation
local states = {}

--- Clear the per-layer state cache.
function LipSync.clear()
	states = {}
end

-- Display name keys for pattern parameters
-- Order: closed -> almost_closed -> half -> almost_open -> open
-- This order matches the animation logic where patterns[1] is closed (default)
-- and patterns[n] is open
local pattern_keys = {
	"閉じ~ptkl",
	"ほぼ閉じ~ptkl",
	"半開き~ptkl",
	"ほぼ開き~ptkl",
	"開き~ptkl",
}

--- Validate that at least 2 patterns are present.
-- @param patterns table: Patterns array
-- @return boolean: true if valid
local function validate(patterns)
	if #patterns < 2 then
		error("LipSync requires at least 2 patterns (closed and open)")
	end
	return true
end

--- Create a new LipSync object from legacy parameters.
-- This function is called from converted anm scripts.
-- @param patterns table: Array of layer state strings (2-5 elements, closed to open)
-- @param sensitivity number: Number of frames for moving average (default: 1)
-- @param alwaysapply boolean: Apply even when no voice data is available
-- @return LipSync object
function LipSync.new_legacy(patterns, sensitivity, alwaysapply)
	local opts = {
		["閉じ~ptkl"] = patterns[1],
		["開き~ptkl"] = patterns[#patterns],
		["感度"] = tostring(sensitivity or 1),
		["発声がなくても有効"] = alwaysapply and "1" or "0",
	}
	if #patterns >= 3 then
		opts["ほぼ閉じ~ptkl"] = patterns[2]
	end
	if #patterns >= 4 then
		opts["半開き~ptkl"] = patterns[3]
	end
	if #patterns >= 5 then
		opts["ほぼ開き~ptkl"] = patterns[4]
	end
	return LipSync.new(opts)
end

--- Creates a new LipSync object.
-- @param opts table: Options table with display name keys
--   Pattern keys (values are layer paths):
--     "閉じ~ptkl": Closed state
--     "ほぼ閉じ~ptkl": Almost closed state (optional)
--     "半開き~ptkl": Half open state (optional)
--     "ほぼ開き~ptkl": Almost open state (optional)
--     "開き~ptkl": Open state
--   Numeric parameters (stored as strings):
--     "ローカット": Low frequency cutoff in Hz (default 100)
--     "ハイカット": High frequency cutoff in Hz (default 1000)
--     "しきい値": Volume threshold for opening mouth (default 20)
--     "感度": Number of frames for moving average (default 1)
--     "発声がなくても有効": Apply even when no voice data is available (0 or 1)
-- @return LipSync: New LipSync object
function LipSync.new(opts)
	if not opts then
		error("opts cannot be nil")
	end

	-- Build patterns array from display name keys
	-- Collect non-empty patterns in order
	local patterns = {}
	for _, key in ipairs(pattern_keys) do
		local value = opts[key]
		if value and value ~= "" then
			table.insert(patterns, value)
		end
	end

	-- Parse numeric parameters (stored as strings)
	local locut = tonumber(opts["ローカット"]) or 100
	local hicut = tonumber(opts["ハイカット"]) or 1000
	local threshold = tonumber(opts["しきい値"]) or 20
	local sensitivity = tonumber(opts["感度"]) or 1

	-- Convert alwaysapply to boolean (stored as "0" or "1")
	local alwaysapply_val = tonumber(opts["発声がなくても有効"]) or 0
	local alwaysapply = alwaysapply_val ~= 0

	return setmetatable({
		patterns = patterns,
		sensitivity = sensitivity,
		alwaysapply = alwaysapply,
		locut = locut,
		hicut = hicut,
		threshold = threshold,
	}, LipSync)
end

--- Calculate moving average volume.
-- @param stat table: State table with vols array
-- @param volume number: Current volume
-- @param time number: Current time
-- @param sensitivity number: Number of frames for moving average
-- @return number: Averaged volume
local function calculate_moving_average(stat, volume, time, sensitivity)
	-- Reset if time goes backwards or jumps too far forward
	-- Allow 1 second tolerance for preview scrubbing
	if stat.time > time or stat.time + 1 < time then
		stat.vols = {}
	end

	-- Add current volume to history
	table.insert(stat.vols, volume)

	-- Keep only the last 'sensitivity' frames
	while #stat.vols > sensitivity do
		table.remove(stat.vols, 1)
	end

	stat.time = time

	-- Calculate average
	local sum = 0
	for _, v in ipairs(stat.vols) do
		sum = sum + v
	end

	return sum / #stat.vols
end

--- Gets the current lip state based on audio volume.
-- This method is called from PSD:buildlayer() during animation rendering.
-- @param ctx table: Context object with get_voice and get_audio_level methods
-- @return string: The layer state string for current lip position
function LipSync:getstate(ctx)
	validate(self.patterns)

	local obj = ctx.obj

	-- Resolve voice_id from ctx.psd.character_id, or fallback to ctx.obj.layer
	local voice_id
	if ctx.psd and ctx.psd.character_id and ctx.psd.character_id ~= "" then
		voice_id = ctx.psd.character_id
	else
		voice_id = obj.layer
	end

	-- Get voice data from context
	local voice = ctx:get_voice(voice_id)

	if voice == nil then
		if self.alwaysapply then
			return self.patterns[1] -- Return closed state
		end
		return ""
	end

	-- Get or initialize per-layer state
	local stat = states[obj.layer]
	if not stat then
		stat = { time = obj.time, pat = 0, vols = {}, voice_obj_id = voice.obj_id }
	end

	-- Reset animation state if voice object changed
	if stat.voice_obj_id ~= voice.obj_id then
		stat = { time = obj.time, pat = 0, vols = {}, voice_obj_id = voice.obj_id }
	end

	-- Reset animation state if time goes backwards or jumps too far forward
	if stat.time > obj.time or stat.time + 1 < obj.time then
		stat.pat = 0
		stat.vols = {}
	end

	-- Get audio level from Voice's pre-captured fourier data (via voice_id)
	local raw_volume = ctx:get_audio_level(voice_id, self.locut, self.hicut)

	-- Apply moving average for smooth animation
	local avg_volume = calculate_moving_average(stat, raw_volume, obj.time, self.sensitivity)

	dbg("LipSync: raw=%.2f avg=%.2f threshold=%.2f pat=%d", raw_volume, avg_volume, self.threshold, stat.pat)

	-- Determine target pattern based on volume vs threshold
	if avg_volume >= self.threshold then
		-- Volume is above threshold - open mouth more
		if stat.pat < #self.patterns - 1 then
			stat.pat = stat.pat + 1
		end
	else
		-- Volume is below threshold - close mouth more
		if stat.pat > 0 then
			stat.pat = stat.pat - 1
		end
	end

	stat.time = obj.time
	states[obj.layer] = stat

	return self.patterns[stat.pat + 1]
end

return LipSync

end

package.preload['PSDToolKit.LipSyncLab'] = function(...)
--- LipSyncLab - Vowel-based lip sync (aiueo)
-- This module provides lip sync animation based on Japanese vowel patterns.
-- Supports lab file phoneme timing data with multiple consonant processing modes.
local LipSyncLab = {}
LipSyncLab.__index = LipSyncLab

local debug = require("PSDToolKit.debug")
local dbg = debug.dbg

-- Per-layer state cache for smooth animation (used by mode 1)
local states = {}

--- Clear the per-layer state cache.
-- Called when project is loaded or cache is cleared.
function LipSyncLab.clear()
	states = {}
end

-- Vowel set for quick lookup
local vowels = {
	a = true,
	i = true,
	u = true,
	e = true,
	o = true,
	A = true,
	I = true,
	U = true,
	E = true,
	O = true,
}

--- Check if phoneme is a vowel
-- @param p string: Phoneme name
-- @return number: 1 if normal vowel, -1 if unvoiced vowel (uppercase), 0 if not vowel
local function isvowel(p)
	if p == "a" or p == "e" or p == "i" or p == "o" or p == "u" then
		return 1
	end
	if p == "A" or p == "E" or p == "I" or p == "O" or p == "U" then
		return -1 -- Unvoiced vowel
	end
	return 0
end

-- Mode 3: Articulation-based mouth shape mapping
-- Maps consonants to the closest vowel shape based on articulation position
local articulation_map = {
	-- Vowels (use as-is, map uppercase to lowercase for pattern lookup)
	a = "a",
	i = "i",
	u = "u",
	e = "e",
	o = "o",
	A = "a",
	I = "i",
	U = "u",
	E = "e",
	O = "o",

	-- Bilabial (lips closed) -> N
	m = "N",
	p = "N",
	b = "N",

	-- Labiodental (lower lip and upper teeth) -> u
	f = "u",
	v = "u",

	-- Alveolar (tongue tip and alveolar ridge)
	t = "u",
	d = "u",
	n = "u",
	s = "i",
	z = "i",
	r = "u",

	-- Alveopalatal (sh, j, ch sounds) -> i (lips spread)
	sh = "i",
	j = "i",
	ch = "i",
	ts = "u",

	-- Palatal -> i (lips spread)
	y = "i",
	hy = "i",
	ny = "i",
	ky = "i",
	gy = "i",
	by = "i",
	py = "i",
	my = "i",
	ry = "i",

	-- Velar (back of tongue) -> u
	k = "u",
	g = "u",
	w = "u",

	-- Glottal -> u
	h = "u",

	-- Special phonemes -> N (closed)
	N = "N", -- Syllabic nasal (ん)
	cl = "N", -- Geminate consonant (っ)
	pau = "N", -- Pause
	sil = "N", -- Silence
}

-- Fallback for unknown phonemes
local UNKNOWN_FALLBACK = "e"

--- Validate that all required patterns are present.
-- @param pat table: Patterns table
-- @return boolean: true if valid
local function validate(pat)
	if pat.a == "" or pat.i == "" or pat.u == "" or pat.e == "" or pat.o == "" or pat.N == "" then
		error("LipSyncLab requires patterns for all vowels: a, i, u, e, o, N")
	end
	return true
end

local consonant_mode_map = {
	["閉じる"] = 0,
	["前を継続"] = 1,
	["前後で補間"] = 2,
	["調音位置"] = 3,
}
local function normalize_consonant_mode(v)
	if type(v) == "number" then
		return v
	end
	if type(v) == "string" then
		local n = tonumber(v)
		if n ~= nil then
			return n
		end
		return consonant_mode_map[v]
	end
	return nil
end

--- Create a new LipSyncLab object from legacy parameters.
-- This function is called from converted anm scripts.
-- @param pat table: Vowel patterns {a=string, i=string, u=string, e=string, o=string, N=string}
-- @param mode number: Consonant processing mode (0, 1, 2, or 3)
-- @param alwaysapply boolean: Apply even when no voice data is available
-- @return LipSyncLab object
function LipSyncLab.new_legacy(pat, mode, alwaysapply)
	local opts = {
		["あ~ptkl"] = pat.a or "",
		["い~ptkl"] = pat.i or "",
		["う~ptkl"] = pat.u or "",
		["え~ptkl"] = pat.e or "",
		["お~ptkl"] = pat.o or "",
		["ん~ptkl"] = pat.N or "",
		["子音処理"] = tostring(mode or 0),
		["発声がなくても有効"] = alwaysapply and "1" or "0",
	}
	return LipSyncLab.new(opts)
end

--- Creates a new LipSyncLab object.
-- @param opts table: Options table with display name keys
--   Pattern keys (values are layer paths):
--     "あ~ptkl": Pattern for vowel 'a'
--     "い~ptkl": Pattern for vowel 'i'
--     "う~ptkl": Pattern for vowel 'u'
--     "え~ptkl": Pattern for vowel 'e'
--     "お~ptkl": Pattern for vowel 'o'
--     "ん~ptkl": Pattern for closed mouth (N/pause)
--   Numeric parameters (stored as strings):
--     "子音処理": Consonant processing mode (0, 1, 2, or 3)
--       0: All consonants -> N (closed)
--       1: Inherit previous vowel (except for certain consonants)
--       2: Interpolate between adjacent vowels
--       3: Articulation-based (map consonants to closest vowel shape)
--     "発声がなくても有効": Apply even when no voice data is available (0 or 1)
-- @return LipSyncLab: New LipSyncLab object
function LipSyncLab.new(opts)
	if not opts then
		error("opts cannot be nil")
	end

	-- Build patterns table from display name keys
	local pat = {
		a = opts["あ~ptkl"] or "",
		i = opts["い~ptkl"] or "",
		u = opts["う~ptkl"] or "",
		e = opts["え~ptkl"] or "",
		o = opts["お~ptkl"] or "",
		N = opts["ん~ptkl"] or "",
	}

	-- Copy uppercase aliases for unvoiced vowels
	pat.A = pat.a
	pat.I = pat.i
	pat.U = pat.u
	pat.E = pat.e
	pat.O = pat.o

	-- Parse parameters ("子音処理" may come as number, numeric string, or caption)
	local mode = normalize_consonant_mode(opts["子音処理"]) or 0

	-- Convert alwaysapply to boolean (stored as "0" or "1")
	local alwaysapply_val = tonumber(opts["発声がなくても有効"]) or 0
	local alwaysapply = alwaysapply_val ~= 0

	-- Note: locut, hicut, threshold are not used in current LipSyncLab
	-- but kept for fallback volume-based detection
	local locut = 100
	local hicut = 1000
	local threshold = 20

	return setmetatable({
		patterns = pat,
		mode = mode,
		alwaysapply = alwaysapply,
		locut = locut,
		hicut = hicut,
		threshold = threshold,
	}, LipSyncLab)
end

--- Get adjacent phoneme from entries
-- @param entries table: Phoneme entries array
-- @param index number: Current index
-- @param offset number: Offset (-1 for previous, +1 for next)
-- @return table|nil: Adjacent entry or nil if out of bounds
local function get_adjacent(entries, index, offset)
	local adj_index = index + offset
	if adj_index < 1 or adj_index > #entries then
		return nil
	end
	return entries[adj_index]
end

--- Mode 0: All consonants become N (closed)
-- @param cur string: Current phoneme
-- @param pat table: Patterns table
-- @return string: Layer state string
function LipSyncLab:process_mode0(cur, pat)
	if isvowel(cur) ~= 0 then
		return pat[cur] or pat.N
	end
	return pat.N
end

--- Mode 1: Inherit previous vowel (except for certain consonants)
-- @param cur string: Current phoneme
-- @param phoneme_info table: Phoneme info from LabFile
-- @param pat table: Patterns table
-- @param obj table: AviUtl object
-- @param voice_obj_id number: Voice object ID for cache invalidation
-- @return string: Layer state string
function LipSyncLab:process_mode1(cur, phoneme_info, pat, obj, voice_obj_id)
	-- Get or initialize per-layer state
	local stat = states[obj.layer]
	if not stat then
		stat = { frame = obj.frame - 1, p = "N", voice_obj_id = voice_obj_id }
	end

	-- Reset if voice object changed
	if stat.voice_obj_id ~= voice_obj_id then
		stat = { frame = obj.frame - 1, p = "N", voice_obj_id = voice_obj_id }
	end

	-- Reset if time goes backwards or jumps too far forward
	if stat.frame >= obj.frame or stat.frame + obj.framerate < obj.frame then
		stat.p = "N"
	end
	stat.frame = obj.frame

	if isvowel(cur) == 1 then
		-- Normal vowel: use it and remember
		stat.p = cur
	elseif cur == "pau" or cur == "N" or cur == "cl" then
		-- Pause / syllabic nasal / geminate -> closed
		stat.p = "N"
	else
		-- Other consonants: keep previous vowel (stat.p unchanged)
	end

	states[obj.layer] = stat
	return pat[stat.p] or pat.N
end

--- Mode 2: Interpolate between adjacent vowels
-- @param cur string: Current phoneme
-- @param phoneme_info table: Phoneme info from LabFile
-- @param pat table: Patterns table
-- @return string: Layer state string
function LipSyncLab:process_mode2(cur, phoneme_info, pat)
	if isvowel(cur) ~= 0 then
		-- Vowel: use as-is
		return pat[cur] or pat.N
	end

	-- Special cases
	if cur == "pau" or cur == "N" or cur == "m" or cur == "p" or cur == "b" or cur == "v" then
		-- Pause / syllabic nasal / bilabial consonants -> closed
		return pat.N
	end

	local entries = phoneme_info.entries
	local index = phoneme_info.index
	local progress = phoneme_info.progress

	-- Get adjacent entries
	local prev_entry = get_adjacent(entries, index, -1)
	local next_entry = get_adjacent(entries, index, 1)

	if cur == "cl" then
		-- Geminate consonant (っ)
		if progress < 0.5 then
			-- First half: use previous vowel if adjacent
			if prev_entry and isvowel(prev_entry.phoneme) ~= 0 then
				local cur_entry = entries[index]
				if prev_entry.end_ == cur_entry.start then
					return pat[prev_entry.phoneme] or pat.N
				end
			end
			return pat.N
		else
			-- Second half: prepare for next vowel with "u" shape
			return pat.u
		end
	end

	-- Default consonant handling: interpolate based on progress
	if progress < 0.5 then
		-- First half: inherit from previous vowel
		if prev_entry and isvowel(prev_entry.phoneme) ~= 0 then
			local cur_entry = entries[index]
			if prev_entry.end_ == cur_entry.start then
				local prev_p = prev_entry.phoneme
				-- Transition to smaller shape
				if prev_p == "a" or prev_p == "A" then
					return pat.o
				elseif prev_p == "i" or prev_p == "I" then
					return pat.i
				else
					return pat.u
				end
			end
		end
		return pat.N
	else
		-- Second half: prepare for next vowel
		if next_entry and isvowel(next_entry.phoneme) ~= 0 then
			local cur_entry = entries[index]
			if next_entry.start == cur_entry.end_ then
				local next_p = next_entry.phoneme
				-- Transition to smaller shape
				if next_p == "a" or next_p == "A" then
					return pat.o
				elseif next_p == "i" or next_p == "I" then
					return pat.i
				else
					return pat.u
				end
			end
		end
		return pat.N
	end
end

--- Mode 3: Articulation-based mapping
-- @param cur string: Current phoneme
-- @param pat table: Patterns table
-- @return string: Layer state string
function LipSyncLab:process_mode3(cur, pat)
	local mapped = articulation_map[cur]
	if mapped then
		return pat[mapped] or pat.N
	end
	-- Unknown phoneme: use fallback
	return pat[UNKNOWN_FALLBACK] or pat.N
end

--- Gets the current lip state based on lab file phoneme data.
-- Falls back to volume-based detection if lab file is not available.
-- @param ctx table: Context object with get_voice, get_audio_level, and get_phoneme methods
-- @return string: The layer state string for current lip position
function LipSyncLab:getstate(ctx)
	local pat = self.patterns

	validate(pat)

	local obj = ctx.obj

	-- Resolve voice_id from ctx.psd.character_id, or fallback to ctx.obj.layer
	local voice_id
	if ctx.psd and ctx.psd.character_id and ctx.psd.character_id ~= "" then
		voice_id = ctx.psd.character_id
	else
		voice_id = obj.layer
	end

	-- Get voice data from context
	local voice = ctx:get_voice(voice_id)

	if voice == nil then
		if self.alwaysapply then
			return pat.N -- Return closed state (ん)
		end
		return ""
	end

	-- Always get volume (for fallback and potential future use)
	local volume = ctx:get_audio_level(voice_id, self.locut, self.hicut)

	-- Try to get phoneme from lab file
	local phoneme_info = ctx:get_phoneme(voice_id)

	dbg(
		"LipSyncLab: volume=%.2f threshold=%.2f phoneme=%s mode=%d",
		volume,
		self.threshold,
		phoneme_info and phoneme_info.phoneme or "(nil)",
		self.mode
	)

	if not phoneme_info then
		-- Fallback: volume-based detection
		if volume >= self.threshold then
			return pat.a
		end
		return pat.N
	end

	local cur = phoneme_info.phoneme

	-- Mode dispatch
	if self.mode == 0 then
		return self:process_mode0(cur, pat)
	elseif self.mode == 1 then
		return self:process_mode1(cur, phoneme_info, pat, obj, voice.obj_id)
	elseif self.mode == 2 then
		return self:process_mode2(cur, phoneme_info, pat)
	elseif self.mode == 3 then
		return self:process_mode3(cur, pat)
	end

	error("unexpected consonant processing mode: " .. tostring(self.mode))
end

return LipSyncLab

end

package.preload['PSDToolKit.OverwriterStates'] = function(...)
--- OverwriterStates for PSDToolKit
-- Manages layer selector overwriter storage and retrieval by character ID or layer number.
-- States are organized by frame number to support multi-frame state management.
local CharacterID = require("PSDToolKit.CharacterID")
local FrameState = require("PSDToolKit.FrameState")

local OverwriterStates = {}
OverwriterStates.__index = OverwriterStates

function OverwriterStates.new()
	return setmetatable({
		states = {}, -- frame_number -> {id_key -> values}
	}, OverwriterStates)
end

--- Clears overwriter states for a specific frame.
-- @param frame_number number: The frame number to clean up
function OverwriterStates:cleanup_frame(frame_number)
	self.states[frame_number] = nil
end

--- Clears all overwriter states (for cache invalidation).
function OverwriterStates:clear_all()
	self.states = {}
end

--- Merge values into existing state or create new state.
-- @param states table: The states table for the current frame
-- @param key string: The state key
-- @param values table: The overwriter values table {p1=number, p2=number, ...}
local function merge_values(states, key, values)
	local existing = states[key]
	if existing then
		-- Merge: later values override earlier ones
		for k, v in pairs(values) do
			existing[k] = v
		end
	else
		-- First assignment: copy values
		local copy = {}
		for k, v in pairs(values) do
			copy[k] = v
		end
		states[key] = copy
	end
end

--- Sets the overwriter state for a given character ID and layer.
-- Multiple calls with the same ID will merge values (later values win).
-- You can also search by layer number even if the id is omitted.
-- @param id string: The character identifier. Can be nil or empty. Multiple IDs can be specified separated by commas.
-- @param layer number: The layer number.
-- @param values table: The overwriter values table {p1=number, p2=number, ...}
function OverwriterStates:set(id, layer, values)
	local frame = FrameState.get_current_frame()
	FrameState.track_frame_access(frame)

	if not self.states[frame] then
		self.states[frame] = {}
	end

	local frame_states = self.states[frame]
	CharacterID.set_callback(id, layer, function(key)
		merge_values(frame_states, key, values)
	end)
end

--- Gets the overwriter state for a given character ID or layer number.
-- Supports comma-separated IDs for fallback search (returns first found).
-- @param id string: The character identifier or layer specifier (e.g., "L1").
-- @return table|nil: The overwriter values table, or nil if not found.
function OverwriterStates:get(id)
	local frame = FrameState.get_current_frame()
	local frame_states = self.states[frame]
	if not frame_states then
		return nil
	end
	return CharacterID.get(frame_states, id)
end

local singleton = OverwriterStates.new()
return singleton

end

package.preload['PSDToolKit.PSD'] = function(...)
--- PSD object for PSDToolKit v2.0.0alpha10 by oov
local config = require("PSDToolKit.config")
local debug = require("PSDToolKit.debug")
local dbg = debug.dbg

local PSD = {}
PSD.__index = PSD

--- Generate unique ID from scene and layer.
-- @param scene number: Scene ID (0-9999)
-- @param layer number: Layer number (0-999999)
-- @return number: Unique ID
function PSD.make_id(scene, layer)
	PSD.LAYER_MAX = 1000000
	PSD.SCENE_MAX = 10000
	if scene < 0 or scene >= PSD.SCENE_MAX then
		error(string.format("scene_id must be 0-%d", PSD.SCENE_MAX - 1))
	end
	if layer < 0 or layer >= PSD.LAYER_MAX then
		error(string.format("layer must be 0-%d", PSD.LAYER_MAX - 1))
	end
	return layer + scene * PSD.LAYER_MAX
end

--- Create a new PSD object.
-- @param id number: Unique identifier (scene * LAYER_MAX + layer)
-- @param file string: Path to PSD file
-- @param tag number: Tag for GUI window linkage
-- @param opt table|nil: Optional parameters {layer=string, scale=number, offsetx=number, offsety=number, character_id=string}
-- @return PSD object
function PSD.new(id, file, tag, opt)
	opt = opt or {}
	local self = setmetatable({
		id = id,
		file = file,
		tag = tag or 0,
		layer = {},
		scale = opt.scale or 1,
		offsetx = opt.offsetx or 0,
		offsety = opt.offsety or 0,
		rendered = false,
		character_id = opt.character_id or "",
	}, PSD)

	-- Add initial layer state if provided
	if opt.layer and opt.layer ~= "" then
		table.insert(self.layer, opt.layer)
	end

	return self
end

--- Add layer state to the PSD object.
-- @param layer string|table: Layer state string or table with getstate method
-- @param index number|nil: If provided with a table, select layer[index]
function PSD:add_state(layer, index)
	if layer == nil then
		return
	end

	if index == nil then
		-- Direct add
		if type(layer) == "string" and layer ~= "" then
			table.insert(self.layer, layer)
		elseif type(layer) == "table" then
			-- Objects like Blinker, LipSync that have getstate method
			table.insert(self.layer, layer)
		end
	else
		-- Select from list by index
		if type(layer) == "table" and type(index) == "number" then
			if index >= 1 and index <= #layer then
				table.insert(self.layer, layer[index])
			end
		end
	end
end

--- Build layer state string from accumulated states.
-- @param obj table: The AviUtl object (for dynamic state resolution)
-- @return string: Concatenated layer state
function PSD:buildlayer(obj)
	if #self.layer == 0 then
		return ""
	end

	-- Create context object for state evaluation
	local Context = require("PSDToolKit.Context")
	local ctx = Context.new(self, obj)

	local result = {}
	for _, v in ipairs(self.layer) do
		local t = type(v)
		if t == "string" then
			table.insert(result, v)
		elseif t == "table" and type(v.getstate) == "function" then
			-- Dynamic state from Blinker, LipSync, LayerSelector, etc.
			-- getstate can return string or array of strings
			local state = v:getstate(ctx)
			if state then
				local st = type(state)
				if st == "string" and state ~= "" then
					table.insert(result, state)
				elseif st == "table" then
					-- Array of strings - merge into result
					for _, s in ipairs(state) do
						if s and s ~= "" then
							table.insert(result, s)
						end
					end
				end
			end
		end
	end

	return table.concat(result, " ")
end

--- Render the PSD image.
-- @param obj table: The AviUtl object
-- @return boolean: true on success
function PSD:draw(obj)
	if self.rendered then
		error("already rendered")
	end
	if not self.file then
		error("no file specified")
	end
	self.rendered = true

	local ptk = obj.module("PSDToolKit")
	if not ptk then
		error("PSDToolKit script module is not available")
	end

	-- Build layer state string
	local layer_str = self:buildlayer(obj)

	-- Get resize quality from config
	local quality = config.get().resize_quality

	-- Call set_props to get cache key, dimensions, and flip flags
	-- modified: indicates whether properties (layer, scale, offset) changed since last call.
	--           This does NOT indicate cache existence. Even if modified=false, cache may not exist
	--           (e.g., after state changes A->B->A, modified=false but cache for A may be evicted).
	-- flip_x, flip_y: flip flags for GPU-side flip processing
	local modified, cachekey_hex, width, height, flip_x, flip_y = ptk.set_props(self.id, self.file, {
		tag = self.tag,
		layer = layer_str,
		scale = self.scale,
		offsetx = self.offsetx,
		offsety = self.offsety,
		quality = quality,
	})
	dbg(
		"PSD:draw: id=%s modified=%s cachekey=%s size=%sx%s flip=%s,%s",
		tostring(self.id),
		tostring(modified),
		tostring(cachekey_hex),
		tostring(width),
		tostring(height),
		tostring(flip_x),
		tostring(flip_y)
	)

	local mw, mh = obj.getinfo("image_max")
	if width > mw then
		width = mw
	end
	if height > mh then
		height = mh
	end

	if modified then
		-- Properties changed, need to draw first
		local ok = ptk.draw(self.id, self.file, width, height, cachekey_hex)
		if not ok then
			error("failed to render image")
		end
	end

	-- Try to load from cache
	obj.load("image", cachekey_hex .. ".ptkcache")

	-- If cache miss and not modified, draw and retry
	if (obj.w == 0 or obj.h == 0) and not modified then
		dbg("PSD:draw: cache miss, rendering")
		local ok = ptk.draw(self.id, self.file, width, height, cachekey_hex)
		if not ok then
			error("failed to render image")
		end
		obj.load("image", cachekey_hex .. ".ptkcache")
	end

	if obj.w == 0 or obj.h == 0 then
		error("failed to load cached image")
	end

	-- Apply GPU-side flip if needed
	if flip_x or flip_y then
		obj.effect("反転", "上下反転", flip_y and 1 or 0, "左右反転", flip_x and 1 or 0)
	end

	return true
end

return PSD

end

package.preload['PSDToolKit.SubObjectStates'] = function(...)
--- SubObjectStates for PSDToolKit
-- Manages sub-object timing information storage and retrieval by character ID or layer number.
-- This is used by animation effects (like bounce) that need timing info from voice or overwriter objects.
-- States are organized by frame number to support multi-frame state management.
local CharacterID = require("PSDToolKit.CharacterID")
local FrameState = require("PSDToolKit.FrameState")

local SubObjectStates = {}
SubObjectStates.__index = SubObjectStates

function SubObjectStates.new()
	return setmetatable({
		states = {}, -- frame_number -> {id_key -> state}
	}, SubObjectStates)
end

--- Clears sub-object states for a specific frame.
-- @param frame_number number: The frame number to clean up
function SubObjectStates:cleanup_frame(frame_number)
	self.states[frame_number] = nil
end

--- Clears all sub-object states (for cache invalidation).
function SubObjectStates:clear_all()
	self.states = {}
end

--- Sets the sub-object state for a given ID and layer.
-- @param id string: The character identifier. Can be nil or empty. Multiple IDs can be specified separated by commas.
-- @param layer number: The layer number.
-- @param obj table: The AviUtl object containing time, frame, totaltime, totalframe.
function SubObjectStates:set(id, layer, obj)
	local frame = FrameState.get_current_frame()
	FrameState.track_frame_access(frame)

	if not self.states[frame] then
		self.states[frame] = {}
	end

	local state = {
		time = obj.time,
		frame = obj.frame,
		totaltime = obj.totaltime,
		totalframe = obj.totalframe,
	}
	CharacterID.set(self.states[frame], id, layer, state)
end

--- Gets the sub-object state for a given ID or layer number.
-- Supports comma-separated IDs for fallback search (returns first found).
-- @param id string: The identifier for the sub-object state.
-- @return table|nil: The sub-object state {time, frame, totaltime, totalframe}, or nil if not found.
function SubObjectStates:get(id)
	local frame = FrameState.get_current_frame()
	local frame_states = self.states[frame]
	if not frame_states then
		return nil
	end
	return CharacterID.get(frame_states, id)
end

local singleton = SubObjectStates.new()
return singleton

end

package.preload['PSDToolKit.ValueCache'] = function(...)
--- ValueCache - Cache for layer selector values
-- Caches factory function results to avoid rebuilding on every frame.
-- Cache is invalidated when cache_index changes (project load or cache clear).
local ValueCache = {}

-- Internal cache storage
local cache = {}

--- Get or create cached value.
-- @param effect_id number: The effect ID from obj.effect_id
-- @param index number: Cache index within the effect (1, 2, 3, ...)
-- @param factory function: Function that returns the value
-- @return any: The cached or newly created value
function ValueCache.get(effect_id, index, factory)
	local key = tostring(effect_id) .. ":" .. tostring(index)
	local cached = cache[key]
	if cached then
		return cached
	end
	cached = factory()
	cache[key] = cached
	return cached
end

--- Clear the cache.
-- Called when cache_index changes (project load or cache clear).
function ValueCache.clear()
	cache = {}
end

return ValueCache

end

package.preload['PSDToolKit.Voice'] = function(...)
local Voice = {}
Voice.__index = Voice

function Voice.new(text, audio, x, y, z, frame, time, totalframe, totaltime, obj_id)
	return setmetatable({
		text = text,
		audio = audio,
		x = x,
		y = y,
		z = z,
		frame = frame,
		time = time,
		totalframe = totalframe,
		totaltime = totaltime,
		obj_id = obj_id, -- Object ID for cache invalidation
		-- Fourier data for current frame
		fourier_data = nil,
		fourier_sample_rate = nil,
	}, Voice)
end

return Voice

end

package.preload['PSDToolKit.VoiceStates'] = function(...)
--- VoiceStates for PSDToolKit
-- Manages voice state storage and retrieval by ID or layer number.
-- States are organized by frame number to support multi-frame state management.
local CharacterID = require("PSDToolKit.CharacterID")
local FrameState = require("PSDToolKit.FrameState")

local VoiceStates = {}
VoiceStates.__index = VoiceStates

function VoiceStates.new()
	return setmetatable({
		states = {}, -- frame_number -> {id_key -> voice}
	}, VoiceStates)
end

--- Clears voice states for a specific frame.
-- @param frame_number number: The frame number to clean up
function VoiceStates:cleanup_frame(frame_number)
	self.states[frame_number] = nil
end

--- Clears all voice states (for cache invalidation).
function VoiceStates:clear_all()
	self.states = {}
end

--- Sets the voice state for a given ID.
-- You can also search by layer number even if the id is omitted.
-- @param id string: The identifier for the voice state. Can be nil or empty. Multiple IDs can be specified separated by commas.
-- @param layer number: The layer number.
-- @param v Voice: The voice state object to set.
function VoiceStates:set(id, layer, v)
	local frame = FrameState.get_current_frame()
	FrameState.track_frame_access(frame)

	if not self.states[frame] then
		self.states[frame] = {}
	end

	CharacterID.set(self.states[frame], id, layer, v)
end

--- Gets the voice state for a given ID or layer number.
-- Supports comma-separated IDs for fallback search (returns first found).
-- @param id string: The identifier for the voice state.
-- @return table: The voice state object, or nil if not found.
function VoiceStates:get(id)
	local frame = FrameState.get_current_frame()
	local frame_states = self.states[frame]
	if not frame_states then
		return nil
	end
	return CharacterID.get(frame_states, id)
end

local singleton = VoiceStates.new()
return singleton

end

package.preload['PSDToolKit.config'] = function(...)
-- Configuration loading for PSDToolKit
local M = {}

local debug = require("PSDToolKit.debug")
local cached_config = nil

--- Get configuration
-- Retrieves and caches config on first call per frame.
-- Also sets debug mode on first call.
-- @return table Config table with debug_mode, cache_index, resize_quality
function M.get()
	if not cached_config then
		local ptk = obj.module("PSDToolKit")
		if not ptk then
			error("PSDToolKit script module is not available")
		end
		local debug_mode, cache_index, resize_quality = ptk.get_render_config()
		if cache_index < 0 then
			error("PSDToolKit initialization failed")
		end
		debug.set_debug(debug_mode)
		cached_config = {
			debug_mode = debug_mode,
			cache_index = cache_index,
			resize_quality = resize_quality,
		}
	end
	return cached_config
end

--- Clear cached configuration
-- Called from init.lua at the start of each frame
function M.clear()
	cached_config = nil
end

return M

end

package.preload['PSDToolKit.debug'] = function(...)
local M = {}

local is_debug = false

--- Update debug mode
-- @param debug boolean Enable/disable debug mode
function M.set_debug(debug)
	is_debug = debug
end

--- Debug print function with lazy formatting
-- Only formats and prints if debug mode is enabled.
-- Usage: local dbg = debug.dbg
--        dbg("format string %s %d", arg1, arg2)
--        dbg("simple message")
-- @param fmt string Format string (passed to string.format if additional arguments exist)
-- @param ... Additional arguments for string.format
function M.dbg(fmt, ...)
	if is_debug then
		if select("#", ...) > 0 then
			debug_print(string.format(fmt, ...))
		else
			debug_print(fmt)
		end
	end
end

return M

end

package.preload['PSDToolKit.easing'] = function(...)
--- Easing functions module for PSDToolKit

local easing = {}

function easing.linear(p)
	return p
end

function easing.sineIn(p)
	return 1 - math.cos(p * math.pi / 2)
end

function easing.sineOut(p)
	return math.sin(p * math.pi / 2)
end

function easing.sineInOut(p)
	return -(math.cos(math.pi * p) - 1) / 2
end

function easing.quadIn(p)
	return p * p
end

function easing.quadOut(p)
	return 1 - (1 - p) * (1 - p)
end

function easing.quadInOut(p)
	return p < 0.5 and 2 * p * p or 1 - (-2 * p + 2) ^ 2 / 2
end

function easing.cubicIn(p)
	return p * p * p
end

function easing.cubicOut(p)
	return 1 - (1 - p) ^ 3
end

function easing.cubicInOut(p)
	return p < 0.5 and 4 * p * p * p or 1 - (-2 * p + 2) ^ 3 / 2
end

function easing.quartIn(p)
	return p * p * p * p
end

function easing.quartOut(p)
	return 1 - (1 - p) ^ 4
end

function easing.quartInOut(p)
	return p < 0.5 and 8 * p * p * p * p or 1 - (-2 * p + 2) ^ 4 / 2
end

function easing.quintIn(p)
	return p * p * p * p * p
end

function easing.quintOut(p)
	return 1 - (1 - p) ^ 5
end

function easing.quintInOut(p)
	return p < 0.5 and 16 * p * p * p * p * p or 1 - (-2 * p + 2) ^ 5 / 2
end

function easing.expoIn(p)
	return p == 0 and 0 or 2 ^ (10 * (p - 1))
end

function easing.expoOut(p)
	return p == 1 and 1 or 1 - 2 ^ (-10 * p)
end

function easing.expoInOut(p)
	if p == 0 then
		return 0
	end
	if p == 1 then
		return 1
	end
	return p < 0.5 and 2 ^ (20 * p - 10) / 2 or (2 - 2 ^ (-20 * p + 10)) / 2
end

function easing.backIn(p)
	local c1 = 1.70158
	local c3 = c1 + 1
	return c3 * p * p * p - c1 * p * p
end

function easing.backOut(p)
	local c1 = 1.70158
	local c3 = c1 + 1
	return 1 + c3 * (p - 1) ^ 3 + c1 * (p - 1) ^ 2
end

function easing.backInOut(p)
	local c1 = 1.70158
	local c2 = c1 * 1.525
	if p < 0.5 then
		return ((2 * p) ^ 2 * ((c2 + 1) * 2 * p - c2)) / 2
	else
		return ((2 * p - 2) ^ 2 * ((c2 + 1) * (p * 2 - 2) + c2) + 2) / 2
	end
end

function easing.elasticIn(p)
	if p == 0 then
		return 0
	end
	if p == 1 then
		return 1
	end
	local c4 = (2 * math.pi) / 3
	return -2 ^ (10 * p - 10) * math.sin((p * 10 - 10.75) * c4)
end

function easing.elasticOut(p)
	if p == 0 then
		return 0
	end
	if p == 1 then
		return 1
	end
	local c4 = (2 * math.pi) / 3
	return 2 ^ (-10 * p) * math.sin((p * 10 - 0.75) * c4) + 1
end

function easing.elasticInOut(p)
	if p == 0 then
		return 0
	end
	if p == 1 then
		return 1
	end
	local c5 = (2 * math.pi) / 4.5
	if p < 0.5 then
		return -(2 ^ (20 * p - 10) * math.sin((20 * p - 11.125) * c5)) / 2
	else
		return (2 ^ (-20 * p + 10) * math.sin((20 * p - 11.125) * c5)) / 2 + 1
	end
end

function easing.bounceOut(p)
	local n1 = 7.5625
	local d1 = 2.75
	if p < 1 / d1 then
		return n1 * p * p
	elseif p < 2 / d1 then
		p = p - 1.5 / d1
		return n1 * p * p + 0.75
	elseif p < 2.5 / d1 then
		p = p - 2.25 / d1
		return n1 * p * p + 0.9375
	else
		p = p - 2.625 / d1
		return n1 * p * p + 0.984375
	end
end

function easing.bounceIn(p)
	return 1 - easing.bounceOut(1 - p)
end

function easing.bounceInOut(p)
	if p < 0.5 then
		return (1 - easing.bounceOut(1 - 2 * p)) / 2
	else
		return (1 + easing.bounceOut(2 * p - 1)) / 2
	end
end

return easing

end

package.preload['PSDToolKit.i18n'] = function(...)
--- i18n module for PSDToolKit v2.0.0alpha10 by oov
local M = {}

-- Cached preferred language list
local preferred_langs = nil

--- Get preferred languages from script module (cached)
-- @return table: Array of language codes (e.g., {"ja_JP", "en_US"})
local function get_preferred_languages()
	if preferred_langs then
		return preferred_langs
	end
	local ptk = obj.module("PSDToolKit")
	if ptk and ptk.get_preferred_languages then
		preferred_langs = ptk.get_preferred_languages()
		if not preferred_langs or #preferred_langs == 0 then
			preferred_langs = { "en_US" }
		end
	else
		preferred_langs = { "en_US" }
	end
	return preferred_langs
end

--- Extract primary language from language code
-- @param code string: Language code (e.g., "ja_JP")
-- @return string: Primary language (e.g., "ja")
local function get_primary_lang(code)
	return string.match(code, "^([^_]+)")
end

--- Select the best matching text from a table based on system language.
-- @param tbl table: Keys are language codes (ja_JP, en_US, etc.), values are text
-- @param override string|nil: Optional language code to override system preference
-- @return string|nil: Selected text
function M.i18n(tbl, override)
	if type(tbl) ~= "table" then
		error("i18n requires a table argument")
	end

	local langs = get_preferred_languages()

	-- If override is provided, prepend it to the language list
	if override and type(override) == "string" then
		local override_langs = { override }
		for _, v in ipairs(langs) do
			table.insert(override_langs, v)
		end
		langs = override_langs
	end

	-- Exact match
	for _, lang in ipairs(langs) do
		if tbl[lang] then
			return tbl[lang]
		end
	end

	-- Primary language match
	for _, lang in ipairs(langs) do
		local primary = get_primary_lang(lang)
		for key, value in pairs(tbl) do
			if get_primary_lang(key) == primary then
				return value
			end
		end
	end

	-- Fallback: en_US, then first entry
	if tbl.en_US then
		return tbl.en_US
	end

	for _, value in pairs(tbl) do
		return value
	end

	return nil
end

return M

end

package.preload['PSDToolKit.util'] = function(...)
local M = {}

--- Gets the byte offset for the nth UTF-8 character in a string.
-- @param s string: The input UTF-8 string.
-- @param pos number: The character position (1-based, positive only).
-- @return number: The byte offset of the character, or #s + 1 if out of bounds.
local function utf8_offset(s, pos)
	if pos == 1 then
		return 1
	end
	local char_count = 0
	local i = 1
	while i <= #s and char_count < pos - 1 do
		local c = s:byte(i)
		if c < 128 then
			i = i + 1
		elseif c < 224 then
			i = i + 2
		elseif c < 240 then
			i = i + 3
		else
			i = i + 4
		end
		char_count = char_count + 1
	end
	if char_count == pos - 1 then
		return i
	else
		return #s + 1
	end
end

--- Gets a substring of a UTF-8 encoded string.
-- @param s string: The input UTF-8 string.
-- @param i number: The starting character position (1-based, positive only).
-- @param j number: The ending character position (1-based, positive only, -1 for end of string, defaults to -1).
-- @return string: The extracted substring, or nil if the input is not valid UTF-8.
local function utf8_sub(s, i, j)
	if not s then
		return nil
	end
	i = i or 1
	j = j or -1
	if i < 1 then
		return ""
	end
	if j ~= -1 and (j < 1 or i > j) then
		return ""
	end
	local start_byte = utf8_offset(s, i)
	if not start_byte then
		return nil
	end
	local end_byte = j == -1 and #s + 1 or utf8_offset(s, j + 1)
	if not end_byte then
		return nil
	end
	return s:sub(start_byte, end_byte - 1)
end

--- Gets a truncated version of s.
-- @param s string: The input string.
-- @param length number: The maximum length of the string.
-- @return string: The truncated string with "..." appended if it exceeds the specified length.
function M.truncate_string(s, length)
	local d = utf8_sub(s, 1, length)
	if #s > #d then
		return d .. "..."
	end
	return s
end

return M

end

--- PSDToolKit v2.0.0alpha10 by oov
local M = {}

local config = require("PSDToolKit.config")
local debug = require("PSDToolKit.debug")
local dbg = debug.dbg
local i18n = require("PSDToolKit.i18n").i18n
local FrameState = require("PSDToolKit.FrameState")
local CurrentPSD = require("PSDToolKit.CurrentPSD")
local Voice = require("PSDToolKit.Voice")
local VoiceStates = require("PSDToolKit.VoiceStates")
local OverwriterStates = require("PSDToolKit.OverwriterStates")
local SubObjectStates = require("PSDToolKit.SubObjectStates")
local Animations = require("PSDToolKit.Animations")
local LabFile = require("PSDToolKit.LabFile")
local LipSync = require("PSDToolKit.LipSync")
local LipSyncLab = require("PSDToolKit.LipSyncLab")
local ValueCache = require("PSDToolKit.ValueCache")
local util = require("PSDToolKit.util")

local empty_sub_object = {
	x = 0,
	y = 0,
	z = 0,
	frame = 0,
	time = 0,
	totalframe = 1,
	totaltime = 1,
	notfound = true,
}

local last_cache_index = nil

--- Handles new frame processing start.
-- Resets per-frame state and initializes the module for the current frame.
function M.new_frame()
	FrameState.clear()
	config.clear()

	-- Clear current frame's OverwriterStates so p=0 overrides take effect on re-render
    OverwriterStates:cleanup_frame(FrameState.get_current_frame())

	-- Clean up old frames based on recent access tracking
	local frames_to_cleanup = FrameState.get_frames_to_cleanup()
	for _, frame in ipairs(frames_to_cleanup) do
		CurrentPSD.cleanup_frame(frame)
		VoiceStates:cleanup_frame(frame)
		OverwriterStates:cleanup_frame(frame)
		SubObjectStates:cleanup_frame(frame)
	end

	local cfg = config.get()

	-- Clear ALL caches when cache_index changes (project load or cache clear)
	if last_cache_index ~= cfg.cache_index then
		ValueCache.clear()
		LabFile.clear()
		LipSync.clear()
		LipSyncLab.clear()
		CurrentPSD.clear_all()
		VoiceStates:clear_all()
		OverwriterStates:clear_all()
		SubObjectStates:clear_all()
		FrameState.clear_all_frames()
		last_cache_index = cfg.cache_index
		dbg("PSDToolKit: cache cleared (cache_index=%d)", cfg.cache_index)
	end
end

--- Execute a function with error handling for PSD scripts.
-- If the function throws an error, it will be caught and displayed
-- using set_psd_error. This is used to wrap auto-generated scripts
-- and animation scripts to provide consistent error handling.
-- @param fn function: The function to execute
function M.psdcall(fn)
	if not FrameState.is_initialized() then
		FrameState.set_error()
		obj.load(
			"text",
			i18n({
				ja_JP = "「最初に置くやつ@PSDToolKit」を配置してください",
				en_US = 'Please place "最初に置くやつ@PSDToolKit" first',
				zh_CN = "请先放置“初始放置项@PSDToolKit”",
			})
		)
		return
	end
	local ok, err = pcall(fn)
	if not ok then
		if FrameState.has_error() then
			return -- Already in error state, don't overwrite
		end
		FrameState.set_error()
		obj.load("text", tostring(err))
	end
end

--- sets Voice state for given id and layer.
-- @param id string: The identifier for the voice state. Can be nil or empty.
-- @param text string: The message text.
-- @param audio string: The audio file.
-- @param obj table: An object containing properties like layer, x, y, z, frame, time, totalframe, totaltime.
function M.set_voice(id, text, audio, obj)
	local v = Voice.new(text, audio, obj.x, obj.y, obj.z, obj.frame, obj.time, obj.totalframe, obj.totaltime, obj.id)

	-- Capture fourier data at this object's time
	if audio and audio ~= "" then
		local n, sample_rate, buf = obj.getaudio(nil, audio, "fourier")
		if n > 0 and buf then
			v.fourier_data = buf
			v.fourier_sample_rate = sample_rate
			v.fourier_n = n
		end
	end

	dbg("VoiceStates:set id=%s layer=%d text=%s audio=%s", id, obj.layer, util.truncate_string(text, 10), audio)
	VoiceStates:set(id, obj.layer, v)
	SubObjectStates:set(id, obj.layer, obj)
end

--- Set layer selector overwriter values for a character ID.
-- This is called by the "パーツ上書き@PSDToolKit" object.
-- @param id string: Character ID (can be nil or empty)
-- @param values table: Overwriter values {p1=number, p2=number, ...}
-- @param obj table: The AviUtl object
function M.set_layer_selector_overwriter(id, values, obj)
	if FrameState.has_error() then
		return
	end
	if not values then
		error("values cannot be nil")
	end
	OverwriterStates:set(id, obj.layer, values)
	SubObjectStates:set(id, obj.layer, obj)
	dbg("PSDToolKit:set_layer_selector_overwriter id=%s layer=%d", tostring(id), obj.layer)
end

--- Prints a message using the voice state for a given ID.
-- @param opts table|nil: Optional parameters for the mes function.
-- @param obj table: An object to pass to the mes function of the voice state.
-- @return table: The voice state object used to print the message.
function M.mes(opts, obj)
	local ok, err = pcall(function()
		if opts == nil then
			error("opts cannot be nil")
		end
		local id = opts.id
		if type(id) ~= "string" and type(id) ~= "number" then
			error("opts.id must be a string or number")
		end
		local vs = VoiceStates:get(id)
		if vs == nil then
			return empty_sub_object
		end
		local text = vs.text
		if opts ~= nil then
			local t = type(opts.modifier)
			if t == "function" then
				text = opts.modifier(text)
			elseif t == "string" and opts.modifier ~= "" then
				text = opts.modifier .. text
			end
		end
		obj.mes(text)
		obj.ox = obj.ox + vs.x
		obj.oy = obj.oy + vs.y
		obj.oz = obj.oz + vs.z
		return vs
	end)
	if not ok then
		mes(tostring(err))
	end
end

M.init_psd = CurrentPSD.init
M.draw_psd = CurrentPSD.draw
M.add_lipsync = CurrentPSD.add_lipsync
M.add_lipsync_lab = CurrentPSD.add_lipsync_lab
M.add_blinker = CurrentPSD.add_blinker
M.add_layer_selector = CurrentPSD.add_layer_selector
M.add_state = CurrentPSD.add_state
M.add_state_legacy = CurrentPSD.add_state_legacy

-- Animation functions (delegated to Animations)
M.bounce = Animations.bounce
M.enter_exit = Animations.enter_exit

return M
